Musikernetzwerk/Musikernetzwerk/Models/Band.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Musikernetzwerk.Models
{
    public class Band
    {
        public int BandID { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string Bandname { get; set; }
        public bool ClosedGroup { get; set; }
        public int? MemberCount { get; set; }
        public int? Skill { get; set; }
        public string Userlanguage { get; set; }
        public int? CityID { get; set; }   
        public string Description { get; set; }

        public Band() : this(-1, "", "", "", false, null, null, "", null, "") { }
        public Band(int bandID, string email, string passwordhash, string bandname, bool closedGroup, int? memberCount, int? skill, string userlanguage, int? cityID,  string description)
        {
            this.BandID = bandID;
            this.Email = email;
            this.PasswordHash = passwordhash;
            this.Bandname = bandname;
            this.ClosedGroup = closedGroup;
            this.MemberCount = memberCount;
            this.Skill = skill;
            this.Userlanguage = userlanguage;
            this.CityID = cityID;   
            this.Description = description;          
        }
    }
}

Musikernetzwerk/Musikernetzwerk/Controllers/SearchAfterMusicianController.cs
using Musikernetzwerk.Models;
using Musikernetzwerk.Models.DB;
using Musikernetzwerk.Models.ViewModels;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Musikernetzwerk.Controllers
{
    public class SearchAfterMusicianController : Controller
    {
        IMusicianSearchRepository musicianSearchRepository;
        ICityRepository cityRepository;
        IBandMemberSearchPropertiesRepository bandMemberSearchPropertiesRepository;
        IBandMemberSearchInstrumentsRepository bandMemberSearchInstrumentsRepository;
        IInstrumentRepository instrumentRepository;

        [HttpGet]
        public ActionResult SearchAfterMusician()
        {
            SearchAfterMusicianModel m = new SearchAfterMusicianModel();
            try
            {
                instrumentRepository = new InstrumentRepository();
                instrumentRepository.Open();

                List<Instrument> i = instrumentRepository.GetAllInstruments();

                if (i != null)
                {
                    m.Instruments = new MultiSelectList(i, "InstrumentID", "De");
                    if (Resources.Resources.Culture != null)
                    {
                        string lang = (string)Resources.Resources.Culture.ToString();
                        if (lang != null)
                        {
                            switch (lang)
                            {
                                case "en":
                                    m.Instruments = new MultiSelectList(i, "InstrumentID", "En");
                                    break;
                                default:
                                    m.Instruments = new MultiSelectList(i, "InstrumentID", "De");
                                    break;
                            }
                        }
                    }
                    Musician user = (Musician)Session["Musician"];
                    if (user != null)
                    {
                        switch (user.Userlanguage)
                        {
                            case "en":
                                m.Instruments = new MultiSelectList(i, "InstrumentID", "En");
                                break;
                            default:
                                m.Instruments = new MultiSelectList(i, "InstrumentID", "De");
                                break;
                        }
                    }
                    if (user == null)
                    {
                        Band user2 = (Band)Session["Band"];
                        if (user2 != null)
                        {
                            switch (user2.Userlanguage)
                            {
                                case "en":
                                    m.Instruments = new MultiSelectList(i, "InstrumentID", "En");
                                    break;
                                default:
                                    m.Instruments = new MultiSelectList(i, "InstrumentID", "De");
                                    break;
                            }
                        }
                    }

                    return View(m);
                }
                else
                {
                    return View("Message", new Message(Resources.Resources.Instrumenten_Fehler, Resources.Resources.Keine_Instrumente_gefunden));
                }

            }
            catch (MySqlException)
            {
                return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
            }
            catch (Exception)
            {
                return View("Message", new Message(Resources.Resources.Allgemeiner_Fehler, Resources.Resources.Es_ist_ein_allgemeiner_Fehler_aufgetreten));
            }

            finally
            {
                instrumentRepository.Close();
            }
        }

        [HttpPost]
        public ActionResult SearchAfterMusician(SearchAfterMusicianModel searchAfterMusicianModel)
        {
            List<SearchAfterMusicianResultModel> SearchResult = new List<SearchAfterMusicianResultModel>();

            if (searchAfterMusicianModel != null)
            {
                try
                {
                    musicianSearchRepository = new MusicianSearchRepository();
                    musicianSearchRepository.Open();

                    if (Session["Musician"] != null)
                    {
                        Musician m = (Musician)Session["Musician"];
                        cityRepository = new CityRepository();
                        cityRepository.Open();
                        City c = cityRepository.GetCity((int)m.CityID);
                        SearchResult = musicianSearchRepository.MusicianSearch(searchAfterMusicianModel, (double)c.Latitude, (double)c.Longitude);
                    }
                    else if (Session["Band"] != null)
                    {
                        Band m = (Band)Session["Band"];
                        Session["SkillMin"] = searchAfterMusicianModel.SkillMin;
                        Session["SkillMax"] = searchAfterMusicianModel.SkillMax;
                        Session["CityDistance"] = searchAfterMusicianModel.CityDistance;
                        Session["ChosenInstrumentIDs"] = searchAfterMusicianModel.ChosenInstrumentIDs;
                        Session["BandID"] = m.BandID;

                        cityRepository = new CityRepository();
                        cityRepository.Open();
                        City c = cityRepository.GetCity((int)m.CityID);
                        SearchResult = musicianSearchRepository.MusicianSearch(searchAfterMusicianModel, (float)c.Latitude, (float)c.Longitude);
                    }
                    else
                    {
                        searchAfterMusicianModel.CityDistance = 0;
                        SearchResult = musicianSearchRepository.MusicianSearch(searchAfterMusicianModel, 0, 0);
                    }
                }

                catch (MySqlException)
                {
                    return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
                }
                catch (Exception)
                {
                    return View("Message", new Message(Resources.Resources.Datenverarbeitungsproblem, Resources.Resources.Versuchen_Sie_es_später_erneut));
                }
                finally
                {
                    if (musicianSearchRepository != null)
                    {
                        musicianSearchRepository.Close();
                    }
                }
            }
            return View("SearchAfterMusicianResult", SearchResult);
        }

        [HttpPost]
        public ActionResult SaveSearch()
        {
            try
            {
                bandMemberSearchPropertiesRepository = new BandMemberSearchPropertiesRepository();
                bandMemberSearchPropertiesRepository.Open();
                bool error = false;
                if (Session["ChosenInstrumentIDs"] == null || Session["SkillMin"] == null || Session["SkillMax"] == null || Session["CityDistance"] == null || Session["BandID"] == null)
                {
                    error = true;
                }
                int? BandID = (int?)Session["BandID"];
                int? SkillMin = (int?)Session["SkillMin"];
                int? SkillMax = (int?)Session["SkillMax"];
                int? CityDistance = (int?)Session["CityDistance"];
                int[] ChosenInstrumentIDs = (int[])Session["ChosenInstrumentIDs"];
                bandMemberSearchPropertiesRepository.InsertBandMemberSearchProperty(new BandMember_SearchProperty(null, BandID, SkillMin, SkillMax, CityDistance));
                List<BandMember_SearchProperty> result = bandMemberSearchPropertiesRepository.GetAllBandMemberSearchPropertiesOfBand((int)BandID);
                int index = 0;
                foreach (BandMember_SearchProperty bs in result)
                {
                    if (bs.CityDistance_max == CityDistance && bs.SkillMin == SkillMin && bs.SkillMax == SkillMax)
                    {
                        break;
                    }
                    index++;
                }
                bandMemberSearchInstrumentsRepository = new BandMemberSearchInstrumentsRepository();
                bandMemberSearchInstrumentsRepository.Open();
                foreach (int id in ChosenInstrumentIDs)
                {
                    bandMemberSearchInstrumentsRepository.InsertBandMemberSearchInstrument(new BandMember_SearchInstrument(result[index].BandMember_SearchId, id));
                }
                if (error)
                    return Json(new { status = "error", message = "error saving Search" });

                return Json(new { status = "success", message = "Search saved" });
            }
            catch (MySqlException)
            {
                return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
            }
            catch (Exception)
            {
                return View("Message", new Message(Resources.Resources.Datenverarbeitungsproblem, Resources.Resources.Versuchen_Sie_es_später_erneut));
            }
            finally
            {
                if (bandMemberSearchInstrumentsRepository != null)
                    bandMemberSearchInstrumentsRepository.Close();
            }
        }
        public ActionResult CurrentSearchesAfterMusician()
        {
            if (Session["Band"] != null)
            {
                bandMemberSearchPropertiesRepository = new BandMemberSearchPropertiesRepository();

Musikernetzwerk/Musikernetzwerk/Views/Band/BandProfile.cshtml
@model Musikernetzwerk.Models.ViewModels.BandModel

<table>
    <tr>
        <td>@Resources.Resources.Bandname:</td>
        <td>@Model.Band.Bandname</td>
    </tr>
    <tr>
        <td>@Resources.Resources.Ort:</td>
        @if (Model.City == null)
        {
            <td>-</td>
        }
        else
        {
            <td>@Model.City.CityName</td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Genre:</td>
        @if (Model.OldChosenGenres == null)
        {
            <td>-</td>
        }
        else
        {
            <td>
                @foreach (var g in Model.OldChosenGenres)
                {
                    <span>@g.De</span><br />
                }
            </td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Mitglieder:</td>
        @if (Model.Musicians == null)
        {
            <td>-</td>
        }
        else
        {
            <td>
                @foreach (var m in Model.Musicians)
                {
                    <span>@m.ArtistName</span><br />
                }
            </td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Mitglieder_Anzahl:</td>
        @if (Model.Musicians == null)
        {
            <td>0</td>
        }
        else
        {
            <td>@Model.Musicians.Count</td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Können:</td>
        <td>@Model.Band.Skill</td>
    </tr>
    <tr>
        <td>@Resources.Resources.E_Mail:</td>
        <td>@Model.Band.Email</td>
    </tr>
</table>
<h2 class="profile-heading">@Resources.Resources.Beschreibung</h2>
<p>@Model.Band.Description</p>

Musikernetzwerk/Musikernetzwerk/Views/Band/ChangeBandDataWithGenres.cshtml
@model Musikernetzwerk.Models.ViewModels.BandModel
@{
    ViewBag.Title = Resources.Resources.Bearbeiten;
}
@Html.Partial("~/Views/Shared/BandForm.cshtml")

Musikernetzwerk/Musikernetzwerk/Views/Band/GetBandPrivate.cshtml
@model Musikernetzwerk.Models.ViewModels.BandModel
@using Musikernetzwerk.Models;
@{
    ViewBag.Title = Resources.Resources.Band;
}
<body style="background: rgba(52,22,75,0.25)">
    <div class="profile-header">
        <img src="../Content/Images/water1.jpg" alt="musician" />
    </div>

    <h2 class="profile-heading">@Resources.Resources.Band: @Model.Band.Bandname</h2>

    <div class="profile-options-private">
        <a href="~/Login/LogoutBand">@Resources.Resources.Ausloggen</a>
        @if (Session["Band"] != null)
        {
            @Html.ActionLink(Resources.Resources.Bearbeiten, "ChangeBandDataWithGenres", "Band")
        }
    </div>
    <div class="profile-features-private">
            <a href="~/Band/GetBandRequests">@Resources.Resources.Anfragen</a> <br />
            <a href="~/Band/GetBandSavedSearches">@Resources.Resources.Gespeicherte_Suchen</a>
    </div>

    <div class="profile-description">
    @Html.Partial("BandProfile")
    </div>
</body>

Musikernetzwerk/Musikernetzwerk/Views/Band/GetBandPublic.cshtml
@model Musikernetzwerk.Models.ViewModels.BandModel
<!-- hier wird der Datentyp angegeben, der für diese View verwendet wird (hier das ViewModel BandModel);
in dieser View wird das öffentliche Profil einer Band angezeigt;
die View empfängt also das oben genannte BandModel;
-->

@using Musikernetzwerk.Models;
@{
    ViewBag.Title = Resources.Resources.Band;
    <!-- angeben des Titels: in der _Layout.cshtml Datei sieht die Titelangabe so aus:
    <title>WeBand - (at)ViewBag.Title</title>
    Resources.Resources.Band: wegen der Mehrsprachigkeit wird die Resource geladen (abhängig von der aktuellen Sprache);
    in diesem Fall lautet die deutsche (und englische) Resource "Band";
    -> der Titel lautet "WeBand - Band"
    -->
}
<body style="background: rgba(52,22,75,0.25)">
    <!-- normaler HTML-Code -->
    <div class="profile-header">
        <img src="../Content/Images/water1.jpg" alt="musician" />
    </div>

    <h2 class="profile-heading">@Resources.Resources.Band: @Model.Band.Bandname</h2>
    <!-- mit (at)Model.Band.Bandname wird auf den geladenen Bandnamen zugegriffen;
    das Kleiner-Zeichen von </h2> ist das Signal für die Umstellung von C/# auf HTML;   
    -->

    <div class="profile-options-public">
        @if (Session["Musician"] != null)
        {
            <button id="band-request-button" onclick="location.href='@Url.Action("SendRequestToBand", "Musician", new { bandid = Model.Band.BandID })'">
                @Resources.Resources.Anfrage_senden
            </button><br />
            <!-- bei Anklicken dieses Buttons wird die serverseitige Methode "SendRequestToBand" im Musician-Controller mit dem Parameter "bandid = Model.Band.BandID" ausgeführt;
            Achtung: der Parametername ("bandid") muss exakt dem der Methode entsprechen    
            -->

        }
        else
        {
            <span class="request-error">@Resources.Resources.Nur_Musiker_Anfrage</span>
        }
        <!-- die if-Abfrage kontorlliert, ob der Benutzer als Musiker angemeldet ist;
        nur Musiker können Anfragen an Bands stellen -> diesen Hinweis erhaltet man im else-Sektor;    
        -->

    </div>

    <div class="profile-description">
    @Html.Partial("BandProfile")
    </div>
</body>

Musikernetzwerk/Musikernetzwerk/Views/Band/GetBandRequests.cshtml
@model List<Musikernetzwerk.Models.ViewModels.MusicianBandRequestModel>
@using Musikernetzwerk.Models.ViewModels;
@{
    ViewBag.Title = Resources.Resources.Anfragen;
}
<body style="background: rgba(52,22,75,0.25)">
    <h2>@Resources.Resources.Anfragen:</h2>
    <table @*class="request-table"*@ class="search-result-table">
        <thead>
            <tr>
                <th>@Resources.Resources.Musiker</th>
                <th>@Resources.Resources.Vorname</th>
                <th>@Resources.Resources.Nachname</th>
                <th colspan="2">@Resources.Resources.Entscheidung</th>
            </tr>
        </thead>
        <tbody>
            @foreach (MusicianBandRequestModel b in Model)
            {
                <tr>
                    <td>@Html.ActionLink(b.Musician.ArtistName, "GetMusicianPublic", "Musician", new { musicianId = b.Musician.MusicianID }, new { @class = "search-result-artistname" })
                    <td>@b.Musician.FirstName</td>
                    <td>@b.Musician.LastName</td>
                    <td>@Html.ActionLink(Resources.Resources.Annehmen, "AcceptRequest", "Band", new { musicianbandRequestId = b.Request.BandRequestID }, new { @class = "accept-request" })</td>
                    <td>@Html.ActionLink(Resources.Resources.Ablehnen, "RejectRequest", "Band", new { musicianbandRequestId = b.Request.BandRequestID }, new { @class = "reject-request" })</td>
                </tr>
            }

        </tbody>

    </table>
</body>

Musikernetzwerk/Musikernetzwerk/Views/Band/GetBandSavedSearches.cshtml
@model List<Musikernetzwerk.Models.ViewModels.BandSavedSearchModel>
@using Musikernetzwerk.Models.ViewModels;
@using Musikernetzwerk.Models;
@using Resources;
@{
    ViewBag.Title = Resources.Gespeicherte_Suchen;
}

<body style="background: rgba(52,22,75,0.25)">
    <h1>@Resources.Gespeicherte_Suchen</h1>
    @if ((Model != null) && (Model.Count >= 1))
    {
        <table class="search-result-table">
            <thead>
                <tr>
                    <th>@Resources.Umkreis_in_km</th>
                    <th>@Resources.min_Können</th>
                    <th>@Resources.max_Können</th>
                    <th>@Resources.Instrumente</th>
                    <th>@Resources.Suche</th>
                    <th>@Resources.Löschen</th>
                </tr>
            </thead>
            <tbody>
                @foreach (BandSavedSearchModel m in Model)
                {
                    <tr>
                        <td>@m.SearchProperty.CityDistance_max</td>
                        <td>@m.SearchProperty.SkillMin</td>
                        <td>@m.SearchProperty.SkillMax</td>
                        <td>
                            @foreach (Instrument i in m.Instruments)
                            {
                                @i.De<br />
                            }
                        </td>
                        <td>
                            @Html.ActionLink(Resources.Suche, "GetSearchAfterModelWithSearchId", "SearchAfterMusician", new { searchid = m.SearchProperty.BandMember_SearchId }, null)
                        </td>
                        <td>
                            @Html.ActionLink(Resources.Löschen, "DeleteSavedSearchOfBand", "Band", new { searchid = m.SearchProperty.BandMember_SearchId }, null)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="search-result-message">-</div>
    }
</body>