Musikernetzwerk/Musikernetzwerk/Models/Musician.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Musikernetzwerk.Models
{
    public class Musician
    {
        public int MusicianID { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? Birthdate { get; set; }
        public int? Skill { get; set; }
        public string Userlanguage { get; set; }
        public int? CityID { get; set; }     
        public string ArtistName { get; set; }
        
        public Musician(): this(-1, "", "", "", "", null, null, "", null, "") { }
        public Musician(int musicianID, string email, string passwordhash, string firstname, string lastname, DateTime? birthdate, int? skill, string userlanguage, int? cityID, string artistname)
        {
            this.MusicianID = musicianID;
            this.Email = email;
            this.PasswordHash = passwordhash;
            this.FirstName = firstname;
            this.LastName = lastname;
            this.Birthdate = birthdate;   
            this.Skill=skill;
            this.Userlanguage = userlanguage;
            this.CityID = cityID;           
            this.ArtistName = artistname;
        }
    }
}

Musikernetzwerk/Musikernetzwerk/Controllers/SearchAfterBandController.cs
using Musikernetzwerk.Models;
using Musikernetzwerk.Models.DB;
using Musikernetzwerk.Models.ViewModels;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Musikernetzwerk.Controllers
{
    public class SearchAfterBandController : Controller
    {
        IBandSearchRepository bandSearchRepository;
        ICityRepository cityRepository;
        IMusicianBandSearchPropertiesRepository bandSearchPropertiesRepository;
        IMusicianBandSearchGenresRepository bandSearchGenresRepository;
        IGenreRepository genreRepository;

        [HttpGet]
        public ActionResult SearchAfterBand()
        {
            SearchAfterBandModel b = new SearchAfterBandModel();
            try
            {
                genreRepository = new GenreRepository();
                genreRepository.Open();

                List<Genre> g = genreRepository.GetAllGenres();

                if (g != null)
                {
                    b.Genres = new MultiSelectList(g, "GenreID", "De");
                    if (Resources.Resources.Culture != null)
                    {
                        string lang = (string)Resources.Resources.Culture.ToString();
                        if (lang != null)
                        {
                            switch (lang)
                            {
                                case "en":
                                    b.Genres = new MultiSelectList(g, "GenreID", "En");
                                    break;
                                default:
                                    b.Genres = new MultiSelectList(g, "GenreID", "De");
                                    break;
                            }
                        }
                    }
                    Band user = (Band)Session["Band"];
                    if (user != null)
                    {
                        switch (user.Userlanguage)
                        {
                            case "en":
                                b.Genres = new MultiSelectList(g, "GenreID", "En");
                                break;
                            default:
                                b.Genres = new MultiSelectList(g, "GenreID", "De");
                                break;
                        }
                    }
                    if (user == null)
                    {
                        Musician user2 = (Musician)Session["Musician"];
                        if (user2 != null)
                        {
                            switch (user2.Userlanguage)
                            {
                                case "en":
                                    b.Genres = new MultiSelectList(g, "GenreID", "En");
                                    break;
                                default:
                                    b.Genres = new MultiSelectList(g, "GenreID", "De");
                                    break;
                            }
                        }
                    }
                    return View(b);
                }
                else
                {
                    return View("Message", new Message(Resources.Resources.Genre_Fehler, Resources.Resources.Keine_Genres_gefunden));
                }

            }
            catch (MySqlException)
            {
                return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
            }
            catch (Exception)
            {
                return View("Message", new Message(Resources.Resources.Allgemeiner_Fehler, Resources.Resources.Es_ist_ein_allgemeiner_Fehler_aufgetreten));
            }

            finally
            {
                genreRepository.Close();
            }
        }

        [HttpPost]
        public ActionResult SearchAfterBand(SearchAfterBandModel searchAfterBandModel)
        {
            List<SearchAfterBandResultModel> SearchResult = new List<SearchAfterBandResultModel>();

            if (searchAfterBandModel != null)
            {
                try
                {
                    bandSearchRepository = new BandSearchRepository();
                    bandSearchRepository.Open();

                    if (Session["Band"] != null)
                    {
                        Band b = (Band)Session["Band"];
                        cityRepository = new CityRepository();
                        cityRepository.Open();
                        City c = cityRepository.GetCity((int)b.CityID);
                        SearchResult = bandSearchRepository.BandSearch(searchAfterBandModel, (double)c.Latitude, (double)c.Longitude);
                    }
                    else if (Session["Musician"] != null)
                    {
                        Musician m = (Musician)Session["Musician"];
                        Session["SkillMin"] = searchAfterBandModel.SkillMin;
                        Session["SkillMax"] = searchAfterBandModel.SkillMax;
                        Session["CityDistance"] = searchAfterBandModel.CityDistance;
                        Session["ChosenGenreIDs"] = searchAfterBandModel.ChosenGenreIDs;
                        Session["MusicianID"] = m.MusicianID;

                        cityRepository = new CityRepository();
                        cityRepository.Open();
                        City c = cityRepository.GetCity((int)m.CityID);
                        SearchResult = bandSearchRepository.BandSearch(searchAfterBandModel, (float)c.Latitude, (float)c.Longitude);
                    }
                    else
                    {
                        searchAfterBandModel.CityDistance = 0;
                        SearchResult = bandSearchRepository.BandSearch(searchAfterBandModel, 0, 0);
                    }
                }

                catch (MySqlException)
                {
                    return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
                }
                catch (Exception)
                {
                    return View("Message", new Message(Resources.Resources.Datenverarbeitungsproblem, Resources.Resources.Versuchen_Sie_es_später_erneut));
                }
                finally
                {
                    if (bandSearchRepository != null)
                    {
                        bandSearchRepository.Close();
                    }
                }
            }
            return View("SearchAfterBandResult", SearchResult);
        }

        [HttpPost]
        public ActionResult saveSearch()
        {
            try
            {
                bandSearchPropertiesRepository = new MusicianBandSearchPropertiesRepository();
                bandSearchPropertiesRepository.Open();
                bool error = false;
                if ((Session["ChosenGenreIDs"] == null) || Session["SkillMin"] == null || Session["SkillMax"] == null || Session["CityDistance"] == null || Session["BandID"] == null)
                {
                    error = true;
                }
                int? MusicianID = (int?)Session["MusicianID"];
                int? SkillMin = (int?)Session["SkillMin"];
                int? SkillMax = (int?)Session["SkillMax"];
                int? MemberCountMin = (int?)Session["MemberCount_Min"];
                int? MemberCountMax = (int?)Session["MemberCount_Max"];
                int? CityDistance = (int?)Session["CityDistance"];
                int[] ChosenGenreIDs = (int[])Session["ChosenGenreIDs"];
                bandSearchPropertiesRepository.InsertMusicianBandSearchProperty(new MusicianBand_SearchProperty(null, MusicianID, SkillMin, SkillMax, MemberCountMin, MemberCountMax, CityDistance));
                List<MusicianBand_SearchProperty> result = bandSearchPropertiesRepository.GetAllMusicianBandSearchPropertiesOfMusician((int)MusicianID);
                int index = 0;
                foreach (MusicianBand_SearchProperty bs in result)
                {
                    if (bs.CityDistance_max == CityDistance && bs.SkillMin == SkillMin && bs.SkillMax == SkillMax)
                    {
                        break;
                    }
                    index++;
                }

                bandSearchGenresRepository = new MusicianBandSearchGenresRepository();
                bandSearchGenresRepository.Open();
                foreach (int id in ChosenGenreIDs)
                {
                    bandSearchGenresRepository.InsertBandSearchGenre(new MusicianBand_SearchGenre(result[index].MusicianBand_SearchID, id));
                }

                if (error)
                    return Json(new { status = "error", message = "error saving Search" });

                return Json(new { status = "success", message = "Search saved" });
            }
            catch (MySqlException)
            {
                return View("Message", new Message(Resources.Resources.Datenbank_Fehler, Resources.Resources.Es_gibt_zurzeit_ein_Datenbankproblem));
            }
            catch (Exception)
            {
                return View("Message", new Message(Resources.Resources.Datenverarbeitungsproblem, Resources.Resources.Versuchen_Sie_es_später_erneut));
            }
        }
        public ActionResult CurrentSearchesAfterBand()
        {
            if (Session["Musician"] != null)
            {
                bandSearchPropertiesRepository = new MusicianBandSearchPropertiesRepository();
                bandSearchPropertiesRepository.Open();
                List<MusicianBand_SearchProperty> model = bandSearchPropertiesRepository.GetAllMusicianBandSearchPropertiesOfMusician(((Musician)Session["Musician"]).MusicianID);

                return View(model);
            }
            else
            {
                RedirectToAction("Home");
            }

Musikernetzwerk/Musikernetzwerk/Views/Musician/ChangeMusicianDataWithInstruments.cshtml
@model Musikernetzwerk.Models.ViewModels.MusicianModel

@{
    ViewBag.Title = Resources.Resources.Bearbeiten;
}
@Html.Partial("~/Views/Shared/MusicianForm.cshtml")

Musikernetzwerk/Musikernetzwerk/Views/Musician/ChangeMusicianDataWithInstrumentsFinal.cshtml
@model Musikernetzwerk.Models.ViewModels.MusicianModel
@using Musikernetzwerk.Models;
@{
    ViewBag.Title = Resources.Resources.Bearbeiten;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body style="background: rgba(52,22,75,0.25)">
    <div>
        @using (Html.BeginForm("ChangeMusicianDataWithInstrumentsFinal","Musician"))
        {
            <table class="search-result-table">
                <thead>
                    <tr>
                        <th>@Resources.Resources.Instrument</th>
                        <th>@Resources.Resources.Können</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.NewChosenInstruments.Count; i++)
                    {
                        <tr>
                            <td>@Model.NewChosenInstruments[i].De</td>
                            <td>
                                @Html.TextBoxFor(m => m.NewChosenInstruments[i].Skill)
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="contact-submit-button">@Resources.Resources.Speichern</button>
                        </td>
                    </tr>
                </tfoot>
            </table>
        }
    </div>
</body>
</html>

Musikernetzwerk/Musikernetzwerk/Views/Musician/GetMusicianPrivate.cshtml
@model Musikernetzwerk.Models.ViewModels.MusicianModel
@using Musikernetzwerk.Models;
@{
    ViewBag.Title = Resources.Resources.Musiker;
}
    <body style="background: rgba(52,22,75,0.25)">
        <div class="profile-header">
            <img src="../Content/Images/water1.jpg" alt="musician" />
        </div>

        <h2 class="profile-heading">@Resources.Resources.Musiker: @Model.Musician.ArtistName</h2>

        <div class="profile-options-private">
            <a href="~/Login/LogoutMusician">@Resources.Resources.Ausloggen</a>
            @if (Session["Musician"] != null)
            {
                @Html.ActionLink(Resources.Resources.Bearbeiten, "ChangeMusicianDataWithInstruments", "Musician")
            }
            <br />
            

        </div>
        <div class="profile-features-private">
            <a href="~/Musician/GetMusicianRequests">@Resources.Resources.Anfragen</a> <br />
            <a href="~/Musician/GetMusicianSavedSearches">@Resources.Resources.Gespeicherte_Suchen</a>
        </div>

        <div class="profile-description">
        @Html.Partial("MusicianProfile")
        </div>
    </body>

Musikernetzwerk/Musikernetzwerk/Views/Musician/GetMusicianPublic.cshtml
@model Musikernetzwerk.Models.ViewModels.MusicianModel
@using Musikernetzwerk.Models;
@{
    ViewBag.Title = Resources.Resources.Musiker;
}
<body style="background: rgba(52,22,75,0.25)">
    <div class="profile-header">
        <img src="../Content/Images/water1.jpg" alt="musician" />
    </div>

    <h2 class="profile-heading">@Resources.Resources.Musiker: @Model.Musician.ArtistName</h2>

    <div class="profile-options-public">
        @if (Session["Band"] != null)
        {
            <button id="musician-request-button" onclick="location.href='@Url.Action("SendRequestToMusician", "Band", new { musicianid = Model.Musician.MusicianID })'">
                @Resources.Resources.Anfrage_senden
            </button><br />
        }
        else
        {
            <span class="request-error">@Resources.Resources.Nur_Bands_Anfrage</span>
        }
    </div>

    <div class="profile-description">
    @Html.Partial("MusicianProfile")
    </div>
</body>

Musikernetzwerk/Musikernetzwerk/Views/Musician/GetMusicianRequests.cshtml
@model List<Musikernetzwerk.Models.ViewModels.BandMemberRequestModel>
@using Musikernetzwerk.Models.ViewModels;
@{
    ViewBag.Title = Resources.Resources.Anfragen;
}
<body style="background: rgba(52,22,75,0.25)">
    <h2>@Resources.Resources.Anfragen:</h2>
    <table class="search-result-table">
        <thead>
            <tr>
                <th>@Resources.Resources.Bandname</th>
                <th colspan="2">@Resources.Resources.Entscheidung</th>
            </tr>
        </thead>
        <tbody>
            @foreach (BandMemberRequestModel b in Model)
            {
            <tr>
                <td>@Html.ActionLink(b.Band.Bandname, "GetBandPublic", "Band", new { bandId = b.Band.BandID }, new { @class = "search-result-artistname" })
                <td>@Html.ActionLink(Resources.Resources.Annehmen, "AcceptRequest", "Musician", new { bandMemberRequestId = b.Request.MemberRequestID }, new { @class = "accept-request" })</td>
                <td>@Html.ActionLink(Resources.Resources.Ablehnen, "RejectRequest", "Musician", new { bandMemberRequestId = b.Request.MemberRequestID  }, new { @class = "reject-request" })</td>
            </tr>
            }
        </tbody>
        
    </table>
</body>

Musikernetzwerk/Musikernetzwerk/Views/Musician/GetMusicianSavedSearches.cshtml
@model List<Musikernetzwerk.Models.ViewModels.MusicianSavedSearchModel>
@using Musikernetzwerk.Models.ViewModels;
@using Musikernetzwerk.Models;
@using Resources;
@{
    ViewBag.Title = Resources.Gespeicherte_Suchen;
}

<body style="background: rgba(52,22,75,0.25)">
    <h1>@Resources.Gespeicherte_Suchen</h1>
    @if ((Model != null) && (Model.Count >= 1))
    {
        <table class="search-result-table">
            <thead>
                <tr>
                    <th>@Resources.Umkreis_in_km</th>
                    <th>@Resources.min_Können</th>
                    <th>@Resources.max_Können</th>
                    <th>@Resources.Genre</th>
                    <th>@Resources.Suche</th>
                    <th>@Resources.Löschen</th>
                </tr>
            </thead>
            <tbody>
                @foreach(MusicianSavedSearchModel m in Model)
                {
                    <tr>
                        <td>@m.SearchProperty.CityDistance_max</td>
                        <td>@m.SearchProperty.SkillMin</td>
                        <td>@m.SearchProperty.SkillMax</td>
                        <td>
                            @foreach (Genre g in m.Genres)
                            {
                                @g.De<br/>
                            }
                        </td>
                        <td>
                            @Html.ActionLink(Resources.Suche, "GetSearchAfterModelWithSearchId", "SearchAfterBand", new { searchid = m.SearchProperty.MusicianBand_SearchID}, null)
                        </td>
                        <td>
                            @Html.ActionLink(Resources.Löschen, "DeleteSavedSearchOfMusician", "Musician", new { searchid = m.SearchProperty.MusicianBand_SearchID }, null)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="search-result-message">-</div>
    }
</body>

Musikernetzwerk/Musikernetzwerk/Views/Musician/MusicianProfile.cshtml
@model Musikernetzwerk.Models.ViewModels.MusicianModel

<table>
    <tr>
        <td>@Resources.Resources.Vorname:</td>
        <td>@Model.Musician.FirstName</td>
    </tr>
    <tr>
        <td>@Resources.Resources.Nachname:</td>
        <td>@Model.Musician.LastName</td>
    </tr>
    <tr>
        <td>@Resources.Resources.Künstlername:</td>
        <td>@Model.Musician.ArtistName</td>
    </tr>
    <tr>
        <td>@Resources.Resources.Ort:</td>
        @if (Model.City == null)
        {
            <td>-</td>
        }
        else
        {
            <td>@Model.City.CityName</td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Instrument:</td>
        @if (Model.OldChosenInstruments == null)
        {
            <td>-</td>
        }
        else
        {
            <td>
                @foreach (var i in Model.OldChosenInstruments)
                {
                    <span>@i.De</span> <br />
                }
            </td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Band:</td>
        @if (Model.Bands == null)
        {
            <td>-</td>
        }
        else
        {
            <td>
                @foreach (var i in Model.Bands)
                {
                    <span>@i.Bandname</span> <br />
                }
            </td>
        }
    </tr>
    <tr>
        <td>@Resources.Resources.Können:</td>
        <td>@Model.Musician.Skill</td>
    </tr>
    <tr>
        <td>@Resources.Resources.Geburtsdatum:</td>
        <td>@Model.Musician.Birthdate.Value.ToShortDateString()</td>
    </tr>
    <tr>
        <td>@Resources.Resources.E_Mail:</td>
        <td>@Model.Musician.Email</td>
    </tr>
</table>